### PR TITLE
User Group Report

### PR DESCRIPTION
**Pull request by d-rita**
This PR adds the functionality to get a user group report. 

**How to test:**

- Create a .env file in the base directory.
- Add `REACT_APP_API_URL="https://osm-stats.hotosm.org"` and `HOST=127.0.0.1`.
- Install dependencies using `npm i`
- Run `npm start`. Go to `http://127.0.0.1:3000/user-report` to test.

**Screenshot:**
Screenshot 2021-11-19 at 15 00 11

### CODE REVIEW

**Review by ramyaragupathy — COMMENTED** [review]
Initial comments:

image

* This page should be accessible only for logged in users
* Download CSV and JSON link both did not return any results

cc @d-rita

**Comment by ramyaragupathy** [comment]
Per discussion I missed mentioning authentication as required to access these reports. @d-rita and I will meet tomorrow to review the acceptance criteria for the user group reports page.

**Comment by d-rita** [comment]
1. I have included the `User Group Report` page among the protected routes.
2. Because of the time restrictions (24 hours max) to the `data-quality/user-report` endpoint, no data was being returned for date ranges exceeding 24 hours. This is being worked on in the `galaxy-api` by @itskshitiz321. I have hence added an error display from the user group results table when there is an issue with file downloads.

**Comment by itskshitiz321** [comment]
Update : Solved it from backend as well @d-rita , Included in PR

**Comment by itskshitiz321** [comment]
**Two Quick Suggestions From me :** 
**1.** We need to change json to Geojson , the data coming from API is in geojson format so that we can directly load that geojson in to JOSM and user can fix those data quality issues , In this picture it should be username.geojson 
image

**2.** While loading user report page data , I am getting No data found for a while and after few seconds I am getting the data back , we need to add some loading options while fetching the data and remove it after we got the data and display it 
image
3. Displaying No Data found message when nothing is returned from API instead of 0
image

**Discussion :** 

1. We are getting data quality issues even though they are fixed 
2. If anyone enters hashtag then result returned should be intersection or Union ?  Same logic should be implemented in all endpoints 
3. Why we are having multiple api calls for multiple users ? for eg : if we have 50 users we will be doing 50 api calls 
cc: @ramyaragupathy @d-rita @omranlm

**Pull request merged**
